name: Publish Nuget Package
on:
  push:
    tags:
      - '*'
env:
  GITHUB_TOKEN: ${{ secrets.EBOADEN_TOKEN }}
jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Dotnet Runtime
        run: sudo apt-get install -y dotnet-runtime-2.1
      - name: Pack and Push Nuget Package
        run: |
          dotnet nuget add source https://nuget.pkg.github.com/eboaden/index.json --name "eboaden Github" --username "eboaden" --password "${GITHUB_TOKEN}" --store-password-in-clear-text
          dotnet restore "FileSignatures/FileSignatures.csproj"
          dotnet restore "FileSignatures.Tests/FileSignatures.Tests.csproj"
          dotnet test "FileSignatures.Tests/FileSignatures.Tests.csproj" -c Release
          export PACKAGE_VERSION=${GITHUB_REF##*/}
          PACKAGE_VERSION=${PACKAGE_VERSION#?}
          dotnet pack "FileSignatures/FileSignatures.csproj" -p:Version=${PACKAGE_VERSION} -p:RepositoryUrl="https://github.com/eboaden/FileSignatures"  -o .
          dotnet nuget push FileSignatures.${PACKAGE_VERSION}.nupkg -k ${GITHUB_TOKEN} -s https://nuget.pkg.github.com/eboaden/index.json